# Uncomment the next line to define a global platform for your project

   source 'https://github.com/MMSuperD/FANSpec.git'
 # source 'https://github.com/CocoaPods/Specs.git'
 # source 'https://cdn.cocoapods.org/'
   source 'https://gitee.com/mirrors/CocoaPods-Specs.git'

 platform :ios, '11.0'

target 'ClassicsDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Masonry'

  pod 'YYModel'
  
  pod 'FMDB'
  
  pod "FANOCBaseConfig"
  # Pods for ClassicsDemo

end
