# Uncomment the next line to define a global platform for your project

# source 'https://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@github.com/MMSuperD/FANSpec.git'
source 'git@github.com:MMSuperD/FANSpec.git'
source 'https://gitee.com/mirrors/CocoaPods-Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

# platform :ios, '11.0'

target 'ClassicsDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#  pod 'FANOCBaseConfig'
  pod 'FANOCBaseConfig',:path => '/Users/fan/Desktop/MyStudy/MyGithub/FANOCBaseConfig'


  pod 'YYModel'
  pod 'AgoraRtcEngine_iOS'
  pod 'LFLiveKit'
  
  # 这个是用来做即时通讯 的第三方库
  pod 'SocketRocket'
  
  pod 'AFNetworking'
  
  # Pods for ClassicsDemo

end
